package com.stee.cctv.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-06-16T13:22:11.924+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebServiceClient(name = "AlarmMgtWebServiceForFels", 
                  wsdlLocation = "http://192.168.1.98:7001/CCS_Alarm_Mgt/AlarmWebServiceForFels?wsdl",
                  targetNamespace = "http://impl.ws.alarm.stee.com/") 
public class AlarmMgtWebServiceForFels extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.alarm.stee.com/", "AlarmMgtWebServiceForFels");
    public final static QName AlarmWebServiceForFelsImplPort = new QName("http://impl.ws.alarm.stee.com/", "AlarmWebServiceForFelsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.98:7001/CCS_Alarm_Mgt/AlarmWebServiceForFels?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlarmMgtWebServiceForFels.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.98:7001/CCS_Alarm_Mgt/AlarmWebServiceForFels?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlarmMgtWebServiceForFels(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlarmMgtWebServiceForFels(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlarmMgtWebServiceForFels() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AlarmMgtWebServiceForFels(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AlarmMgtWebServiceForFels(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AlarmMgtWebServiceForFels(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IAlarmWebServiceForFels
     */
    @WebEndpoint(name = "AlarmWebServiceForFelsImplPort")
    public IAlarmWebServiceForFels getAlarmWebServiceForFelsImplPort() {
        return super.getPort(AlarmWebServiceForFelsImplPort, IAlarmWebServiceForFels.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAlarmWebServiceForFels
     */
    @WebEndpoint(name = "AlarmWebServiceForFelsImplPort")
    public IAlarmWebServiceForFels getAlarmWebServiceForFelsImplPort(WebServiceFeature... features) {
        return super.getPort(AlarmWebServiceForFelsImplPort, IAlarmWebServiceForFels.class, features);
    }

}
