
package com.stee.cctv.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.6 2016-06-16T13:22:11.517+08:00
 * Generated source version: 3.0.6
 * 
 */
public final class IAlarmWebServiceForFels_AlarmWebServiceForFelsImplPort_Client {

	private static final QName SERVICE_NAME = new QName("http://impl.ws.alarm.stee.com/", "AlarmMgtWebServiceForFels");

	private IAlarmWebServiceForFels_AlarmWebServiceForFelsImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = AlarmMgtWebServiceForFels.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		AlarmMgtWebServiceForFels ss = new AlarmMgtWebServiceForFels(wsdlURL, SERVICE_NAME);
		IAlarmWebServiceForFels port = ss.getAlarmWebServiceForFelsImplPort();

		{
			System.out.println("Invoking updateFelsAlarm...");
			com.stee.cctv.ws.client.AlarmType _updateFelsAlarm_alarmType = null;
			java.util.List<com.stee.cctv.ws.client.Alarm> _updateFelsAlarm_alarms = null;
			java.lang.String _updateFelsAlarm__return = port.updateFelsAlarm(_updateFelsAlarm_alarmType,
					_updateFelsAlarm_alarms);
			System.out.println("updateFelsAlarm.result=" + _updateFelsAlarm__return);

		}

		System.exit(0);
	}

}
